### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by sonyhome** [cimi/d3-flame-graphs#67]
I see a display bug:
When displaying the following I see ALPHA/BETA/GAMMA write over ROOT (aka 1st layer draws over its root). This looks like an off-by-one index bug:
* Clicking any function does the same and that layer overwrites its root.
* You can't click a function if it doesn't have at least one child layer above itself.

I would like to use you library over Spiermar's because it works with D3 v3, and I already have NVD3 graphs in my project.

 I would greatly appreciate your help - Am I missing something when coding an example? :)

`      <title>D3 Flame Graph</title>
    <div id="d3-flame-graph"></div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3-tip/0.6.7/d3-tip.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/d3-flame-graphs@3.1.1/dist/d3-flame-graph.min.css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/d3-flame-graphs@3.1.1/dist/d3-flame-graph.min.js"></script>
    <script>
    
        var genData = {
        "name": "*ROOT*",
        "value": 7111,
        "children": [
          {
            "name": "ALPHA",
            "value": 4005,
            "children": [
              {
                "name": "one",
                "value": 1500
              },
              {
                "name": "two",
                "value": 200
              },
              {
                "name": "three",
                "value": 1900,
                "children": [
                  {
                    "name": "31337",
                    "value": 100
                  }
                ]
              },
              {
                "name": "four",
                "value": 100
              },
              {
                "name": "five",
                "value": 100
              }
            ]
          },
          {
            "name": "BETA",
            "value": 100,
            "children": [
              {
                "name": "seis",
                "value": 100
              }
            ]
          },
          {
            "name": "GAMMA",
            "value": 100
          } ]
        };
    
        fg = d3.flameGraph('#d3-flame-graph', genData)
          .size([600, 100])
          .cellHeight(20)
          .zoomEnabled(true);
        fg.render();
    </script>
`

**Comment by cimi** [comment]
Hi there, thanks for reporting and sorry for the late reply!

I'll try out your example this weekend and get back to you.

**Comment by cimi** [comment]
The display is broken because the input is missing the `children` property on some of its nodes. Try converting your input to:

```json
{
  "name": "*ROOT*",
  "value": 7111,
  "children": [
    {
      "name": "ALPHA",
      "value": 4005,
      "children": [
        {
          "name": "one",
          "value": 1500,
          "children": []
        },
        {
          "name": "two",
          "value": 200,
          "children": []
        },
        {
          "name": "three",
          "value": 1900,
          "children": [
            {
              "name": "31337",
              "value": 100,
              "children": []
            }
          ]
        },
        {
          "name": "four",
          "value": 100,
          "children": []
        },
        {
          "name": "five",
          "value": 100,
          "children": []
        }
      ]
    },
    {
      "name": "BETA",
      "value": 100,
      "children": [
        {
          "name": "seis",
          "value": 100,
          "children": []
        }
      ]
    },
    {
      "name": "GAMMA",
      "value": 100,
      "children": []
    }
  ]
}
```


Since D3v3 requires adding filler nodes so that the tree displays correctly, the code differentiates between those and normal nodes [by checking the `children` property on a node](https://github.com/cimi/d3-flame-graphs/blob/master/src/d3-flame-graph.coffee#L5-L19).

This could potentially be refactored to remove this requirement, but please try the updated input and let me know if you see other problems.

**Comment by sonyhome** [comment]
Oh OK. Is that all it is? I can easillly make sure leaf nodes have empty
children.

You might want to put a note in the documentation about this. It's
different from Spierman's library behavior.

I will check that this weekend.

DT from gmail.

**Comment by sonyhome** [comment]
Confirmed:

This display bug appears when the leaf nodes do not define an empty  "children: []" element.

**Comment by cimi** [comment]
Cool! I've updated the docs. https://github.com/cimi/d3-flame-graphs/commit/45d5555d25c7253d6562bb4aed427ae8179334c3
